//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3082.
// 
#pragma warning disable 1591

namespace Prototipo_Workspace.dll.Patrimonio {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItensSoap", Namespace="http://www.pece.org.br/")]
    public partial class Itens : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IncluirResgistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObterRegistrosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Itens() {
            this.Url = global::Prototipo_Workspace.dll.Properties.Settings.Default.Prototipo_Workspace_dll_Patrimonio_Itens;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IncluirResgistroCompletedEventHandler IncluirResgistroCompleted;
        
        /// <remarks/>
        public event ObterRegistrosCompletedEventHandler ObterRegistrosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/IncluirRegistro", RequestElementName="IncluirRegistro", RequestNamespace="http://www.pece.org.br/", ResponseElementName="IncluirRegistroResponse", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Msg_Resposta", IsNullable=true)]
        public Response IncluirResgistro([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Request Item) {
            object[] results = this.Invoke("IncluirResgistro", new object[] {
                        Item});
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void IncluirResgistroAsync(Request Item) {
            this.IncluirResgistroAsync(Item, null);
        }
        
        /// <remarks/>
        public void IncluirResgistroAsync(Request Item, object userState) {
            if ((this.IncluirResgistroOperationCompleted == null)) {
                this.IncluirResgistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIncluirResgistroOperationCompleted);
            }
            this.InvokeAsync("IncluirResgistro", new object[] {
                        Item}, this.IncluirResgistroOperationCompleted, userState);
        }
        
        private void OnIncluirResgistroOperationCompleted(object arg) {
            if ((this.IncluirResgistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IncluirResgistroCompleted(this, new IncluirResgistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.pece.org.br/ObterRegistros", RequestNamespace="http://www.pece.org.br/", ResponseNamespace="http://www.pece.org.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Msg_Resposta", IsNullable=true)]
        public Response ObterRegistros() {
            object[] results = this.Invoke("ObterRegistros", new object[0]);
            return ((Response)(results[0]));
        }
        
        /// <remarks/>
        public void ObterRegistrosAsync() {
            this.ObterRegistrosAsync(null);
        }
        
        /// <remarks/>
        public void ObterRegistrosAsync(object userState) {
            if ((this.ObterRegistrosOperationCompleted == null)) {
                this.ObterRegistrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObterRegistrosOperationCompleted);
            }
            this.InvokeAsync("ObterRegistros", new object[0], this.ObterRegistrosOperationCompleted, userState);
        }
        
        private void OnObterRegistrosOperationCompleted(object arg) {
            if ((this.ObterRegistrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObterRegistrosCompleted(this, new ObterRegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Request {
        
        private Objeto[] colecaoObjetosField;
        
        /// <remarks/>
        public Objeto[] ColecaoObjetos {
            get {
                return this.colecaoObjetosField;
            }
            set {
                this.colecaoObjetosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Objeto {
        
        private int objIdField;
        
        private string campoField;
        
        private string valorField;
        
        /// <remarks/>
        public int ObjId {
            get {
                return this.objIdField;
            }
            set {
                this.objIdField = value;
            }
        }
        
        /// <remarks/>
        public string Campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pece.org.br/")]
    public partial class Response {
        
        private int cod_statusField;
        
        private string msg_erroField;
        
        private Objeto[] colecaoObjetosField;
        
        /// <remarks/>
        public int Cod_status {
            get {
                return this.cod_statusField;
            }
            set {
                this.cod_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Msg_erro {
            get {
                return this.msg_erroField;
            }
            set {
                this.msg_erroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Objeto[] ColecaoObjetos {
            get {
                return this.colecaoObjetosField;
            }
            set {
                this.colecaoObjetosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void IncluirResgistroCompletedEventHandler(object sender, IncluirResgistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IncluirResgistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IncluirResgistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void ObterRegistrosCompletedEventHandler(object sender, ObterRegistrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObterRegistrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObterRegistrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591